# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b0fc70e004000872b07f7bdb8e88870bf0bcaefe82552766fa287d85d874ee9aa55c711115cb0aa8aa0833033a2bee1a2fae83d97057a2ab1eda983886e289c

test:
  secret_key_base: 4c9852c19135149198e37a9465c2479f7f52902211058d0f70a45e81553f532c9813fce0325b1e0ba63790ef6abf221b22d2fcb6bed4d3ef05b50e090b00cda0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
